text_size = 8
text_font="data/unscii-8.ttf"
text_color = 0x887ecb
input_color = 0x887ecb
background_color=0x50459b
border_color=0x887ecb
cursor_color=0x887ecb
inline_input=true
use_scanlines=true
window_width=1200
window_height=960
scale=3

layout="""
<window layout="vert">
  <border layout="vert" border="40">
    <main/>
  </border>
</window>
"""
